routes/web.php
<?php

use App\Http\Controllers\ExploreController;
use App\Http\Controllers\FollowsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TweetLikesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::post(
        '/tweets',
        [\App\Http\Controllers\TweetController::class, 'store']
    );
    Route::get(
        '/tweets',
        [\App\Http\Controllers\TweetController::class, 'index']
    )->name('home');

    Route::post(
        '/tweets/{tweet}/like',
        [TweetLikesController::class , 'store']
    );

    Route::delete(
        '/tweets/{tweet}/like',
        [TweetLikesController::class , 'destroy']
    );

    Route::post(
        '/profiles/{user:username}/follow',
        [FollowsController::class, 'store']
    )->name('follow');
    Route::get(
        '/profiles/{user:username}/edit',
        [ProfileController::class, 'edit']
    )->middleware('can:edit,user');

    Route::patch(
        '/profiles/{user:username}',
        [ProfileController::class, 'update']
    )->name('profile')
        ->middleware('can:edit,user');

    Route::get(
        '/explore',
        ExploreController::class
    );

});

Route::get('/profiles/{user:username}',
    [ProfileController::class, 'show'])
    ->name('profile');


Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class User extends Authenticatable
{
    use HasFactory, Notifiable , Followable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function tweets()
    {
        return $this->hasMany(Tweet::class)->latest();
    }

    public function likes()
    {
        return $this->hasMany(Like::class);
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public function getAvatarAttribute($path): string
    {
        return $path ? Storage::url($path) : "https://i.pravatar.cc/200?u=" . $this->email;
    }

    public function timeline()
    {
        $friends = $this->follows()->pluck('id');

        return Tweet::whereIn('user_id' , $friends)
            ->orWhere('user_id' , $this->id)
            ->withLikes()
            ->latest()
            ->paginate(50);
    }

    public function path($append = '')
    {
        $path = route('profile' , $this->username);

        return $append ? $path . "/" . $append : $path;
    }

}

resources/views/_friends-list.blade.php
<div class="bg-gray-200 border border-gray-300 rounded-lg py-4 px-6">
    <h3 class="font-bold text-xl mb-4">Following</h3>

    <ul>
        @forelse(auth()->user()->follows as $user)
            <li class="{{ $loop->last ? '' : 'mb-4' }}">
                <div>
                    <a
                        href="{{ route('profile' , $user) }}"
                        class="flex items-center text-sm"
                    >
                        <img
                            src="{{ $user->avatar }}"
                            alt=""
                            class="rounded-full mr-2"
                            width="50"
                            height="50"
                        >
                        {{ $user->name }}
                    </a>
                </div>
            </li>
        @empty
            <li>No friends yet!</li>
        @endforelse
    </ul>
</div>

resources/views/_publish-tweet-panel.blade.php
<div class="border border-blue-400 rounded-lg px-8 py-6 mb-8">
    <form method="POST" action="/tweets">
        @csrf

        <textarea
            name="body"
            class="w-full outline-none"
            placeholder="what's up ? "
            required
        ></textarea>

        <hr class="my-4">

        <footer class="flex justify-between items-center">
            <img
                src="{{ auth()->user()->avatar }}"
                alt="your avatar"
                class="rounded-full mr-2"
                width="50"
                height="50"
            >
            <button
                type="submit"
                class="bg-blue-500 hover:bg-blue-600 rounded-lg shadow h-10 px-10 text-white text-sm">
                Tweet something ..
            </button>
        </footer>
    </form>

    @error('body')
        <p class="text-red-500 text-sm mt-2">{{ $message }}</p>
    @enderror

</div>

resources/views/_sidebar-links.blade.php
<ul>
    <li>
        <a
            class="font-bold text-lg mb-4 block"
            href="{{ route('home') }}"
        >
            Home
        </a>
    </li>

    <li>
        <a
            class="font-bold text-lg mb-4 block"
            href="/explore"
        >
            Explore
        </a>
    </li>

    @auth
        <li>
            <a
                class="font-bold text-lg mb-4 block"
                href="{{ route('profile' , auth()->user() ) }}"
{{--                href="{{ current_user()->path() }}"--}}
            >
                Profile
            </a>
        </li>

        <li>
            <form method="POST" action="/logout">
                @csrf

                <button class="font-bold text-lg">Logout</button>
            </form>
        </li>
    @endauth
</ul>

resources/views/_timeline.blade.php
<div class="border border-gray-300 rounded-lg">
    @forelse ($tweets as $tweet)
        @include('_tweet')
    @empty
        <p class="p-4">No tweets yet</p>
    @endforelse

    {{ $tweets->links() }}

</div>

resources/views/_tweet.blade.php
<div class="flex p-4 {{ $loop->last ? '' : 'border-b border-b-gray-400' }}">
    <div class="mr-2 flex-shrink-0">
        <a href="{{ $tweet->user->path() }}">
            <img
                src="{{ $tweet->user->avatar }}"
                alt=""
                class="rounded-full mr-2"
                width="50"
                height="50"
            >
        </a>
    </div>
    <div>
        <a href="{{ $tweet->user->path() }}">
            <h5 class="font-bold mb-4">
                {{ $tweet->user->name }}
            </h5>
        </a>

        <p class="text-sm">
            {{ $tweet->body }}
        </p>

        @auth
            <x-like-buttons :tweet="$tweet" />
        @endauth

    </div>
</div>

resources/views/explore.blade.php
<x-app>
    <div>
        @foreach($users as $user)
        <a href="{{ $user->path() }}" class="flex items-center mb-5">
                <img
                    src="{{ $user->avatar }}"
                    alt="{{ $user->username }}'s avatar"
                    width="60"
                    class="mr-4 rounded"
                >
            <div>
                <h4 class="font-bold">{{ '@' . $user->username }}</h4>
            </div>
        </a>
        @endforeach

        {{ $users->links() }}
    </div>
</x-app>